# Generated by Django 4.1.5 on 2023-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_beat_parsing', '0003_alter_quotes_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='author',
        ),
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.ManyToManyField(to='celery_beat_parsing.author'),
        ),
    ]
