# Generated by Django 4.1.5 on 2023-02-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_beat_parsing', '0004_remove_quotes_author_quotes_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='author',
        ),
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='celery_beat_parsing.author'),
        ),
    ]
