# Generated by Django 4.1.5 on 2023-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0003_logmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
