# Generated by Django 4.1.5 on 2023-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0004_alter_logmodel_data_alter_logmodel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='method',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
