# Generated by Django 4.1.5 on 2023-02-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0005_alter_logmodel_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='title',
            field=models.CharField(default='Log', max_length=60),
        ),
    ]
