# Generated by Django 4.1.5 on 2023-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0008_alter_logmodel_body_alter_logmodel_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='body',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='query',
            field=models.TextField(default=None),
        ),
    ]
