# Generated by Django 4.1.5 on 2023-02-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0011_alter_logmodel_body_alter_logmodel_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmodel',
            old_name='create',
            new_name='created',
        ),
    ]
