# Generated by Django 4.1.5 on 2023-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0002_alter_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
