# Generated by Django 4.1.5 on 2023-02-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0003_alter_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
