# Generated by Django 4.1.5 on 2023-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0004_alter_book_pages_alter_book_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
