# Generated by Django 4.1.5 on 2023-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_country_developer_game_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
    ]
